package horizon.skyblock.utilities.island;

public enum IslandPermission {

    ALL, DESTROY_BLOCKS, PLACE_BLOCKS, ANVIL_USE, ARMOR_STAND_USE, BEACON_USE,
    BED_USE, ANIMAL_BREEDING, BREWING_STAND_USE, BUCKET_USE, WATER_COLLECTION,
    ACCESS_STORAGE, WORKBENCH_USE, CROP_TRAMPLING, DOOR_USE, GATE_USE, PROJECTILE_LAUNCH,
    ENCHANTMENT_TABLE_USE, FIRE_EXTINGUISH, FURNACE_USE, ACCESS_HORSE_INVENTORY,
    MOB_RIDING, MONSTER_HURTING, MOB_HURTING, MOB_TAMING, LEASH_USE, LEVER_BUTTON_USE,
    MILKING, JUKEBOX_USE, PRESSURE_PLATE_USE, REDSTONE_USE, MOB_SHEARING, VILLAGER_TRADING,
    ITEM_DROP, ITEM_PICKUP, FISHING, DROPPER_DISPENSER_USE, SPAWN_EGGS, HANGING_DESTROY,
    CAKE_CONSUMPTION, DRAGON_EGG_USE, MINECART_BOAT_USE, PORTAL_USE, HOPPER_USE,
    ENTITY_PLACEMENT, EXPERIENCE_ORB_PICKUP, NONE

}
